apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: GroupRoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/grouproleassignment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    projectId: ${var.project_id}
    roleIdSelector:
      matchLabels:
        testing.upbound.io/example-name: huaweicloud_identity_role

---

apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/grouproleassignment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: group_1
