apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: Provider
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/provider
  labels:
    testing.upbound.io/example-name: provider_1
  name: provider-1
spec:
  forProvider:
    metadata: ${file("/usr/local/data/files/metadata.txt")}
    name: example_com_provider_saml
    protocol: saml
