apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/user
  labels:
    testing.upbound.io/example-name: user_1
  name: user-1
spec:
  forProvider:
    description: A user
    name: user_1
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
