apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: UserRoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/userroleassignment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    enterpriseProjectId: ${var.enterprise_project_id}
    roleIdSelector:
      matchLabels:
        testing.upbound.io/example-name: huaweicloud_identity_role
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: iam.huaweicloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/userroleassignment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: A user
    name: user_1
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
