apiVersion: tcmq.tencentcloud.crossplane.io/v1alpha1
kind: Subscribe
metadata:
  annotations:
    meta.upbound.io/example-id: tcmq/v1alpha1/subscribe
  labels:
    testing.upbound.io/example-name: subscribe
  name: subscribe
spec:
  forProvider:
    endpointSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    protocol: http
    subscriptionName: subscription_name
    topicNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
