apiVersion: cvm.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: cvm/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    dataDisks:
    - dataDiskSize: 50
      dataDiskType: CLOUD_PREMIUM
      encrypt: false
    hostname: user
    imageId: ${data.tencentcloud_images.images.images.0.image_id}
    instanceName: tf-example
    instanceType: ${data.tencentcloud_instance_types.types.instance_types.0.instance_type}
    projectId: 0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    systemDiskSize: 50
    systemDiskType: CLOUD_PREMIUM
    tags:
      tagKey: tagValue
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: cvm/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: subnet
  name: subnet
spec:
  forProvider:
    availabilityZone: ${var.availability_zone}
    cidrBlock: 10.0.1.0/24
    name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc

---

apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: cvm/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    name: vpc
