// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccountPermissionInitParameters struct {

	// Specifies the access to acl. Valid values are READ_ACP and WRITE_ACP.
	// Specifies the access to acl. Valid values are **READ_ACP** and **WRITE_ACP**.
	AccessToACL []*string `json:"accessToAcl,omitempty" tf:"access_to_acl,omitempty"`

	// Specifies the access to object. Only READ supported.
	// Specifies the access to object. Only **READ** supported.
	AccessToObject []*string `json:"accessToObject,omitempty" tf:"access_to_object,omitempty"`

	// Specifies the account id to authorize. The account id cannot be the object owner,
	// and must be unique.
	// Specifies the account id to authorize. The account id cannot be the object owner,
	// and must be unique.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`
}

type AccountPermissionObservation struct {

	// Specifies the access to acl. Valid values are READ_ACP and WRITE_ACP.
	// Specifies the access to acl. Valid values are **READ_ACP** and **WRITE_ACP**.
	AccessToACL []*string `json:"accessToAcl,omitempty" tf:"access_to_acl,omitempty"`

	// Specifies the access to object. Only READ supported.
	// Specifies the access to object. Only **READ** supported.
	AccessToObject []*string `json:"accessToObject,omitempty" tf:"access_to_object,omitempty"`

	// Specifies the account id to authorize. The account id cannot be the object owner,
	// and must be unique.
	// Specifies the account id to authorize. The account id cannot be the object owner,
	// and must be unique.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`
}

type AccountPermissionParameters struct {

	// Specifies the access to acl. Valid values are READ_ACP and WRITE_ACP.
	// Specifies the access to acl. Valid values are **READ_ACP** and **WRITE_ACP**.
	// +kubebuilder:validation:Optional
	AccessToACL []*string `json:"accessToAcl,omitempty" tf:"access_to_acl,omitempty"`

	// Specifies the access to object. Only READ supported.
	// Specifies the access to object. Only **READ** supported.
	// +kubebuilder:validation:Optional
	AccessToObject []*string `json:"accessToObject,omitempty" tf:"access_to_object,omitempty"`

	// Specifies the account id to authorize. The account id cannot be the object owner,
	// and must be unique.
	// Specifies the account id to authorize. The account id cannot be the object owner,
	// and must be unique.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId" tf:"account_id,omitempty"`
}

type OBSInitParameters_2 struct {

	// Specifies the object account permissions.
	// The account_permission_struct structure is documented below.
	// Specifies the object account permissions.
	AccountPermission []AccountPermissionInitParameters `json:"accountPermission,omitempty" tf:"account_permission,omitempty"`

	// Specifies the name of the bucket which the object belongs to.
	// Specifies the name of the bucket which the object belongs to.
	// +crossplane:generate:reference:type=OBS
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a OBS to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a OBS to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	// Specifies the name of the object to which to set the acl.
	// Specifies the name of the object to which to set the acl.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Specifies the object public permission.
	// The permission_struct structure is documented below.
	// Specifies the object public permission.
	PublicPermission []PublicPermissionInitParameters `json:"publicPermission,omitempty" tf:"public_permission,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type OBSObservation_2 struct {

	// Specifies the object account permissions.
	// The account_permission_struct structure is documented below.
	// Specifies the object account permissions.
	AccountPermission []AccountPermissionObservation `json:"accountPermission,omitempty" tf:"account_permission,omitempty"`

	// Specifies the name of the bucket which the object belongs to.
	// Specifies the name of the bucket which the object belongs to.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// The name of the bucket object key.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the name of the object to which to set the acl.
	// Specifies the name of the object to which to set the acl.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The object owner permission information.
	// The owner_permission_struct structure is documented below.
	OwnerPermission []OwnerPermissionObservation `json:"ownerPermission,omitempty" tf:"owner_permission,omitempty"`

	// Specifies the object public permission.
	// The permission_struct structure is documented below.
	// Specifies the object public permission.
	PublicPermission []PublicPermissionObservation `json:"publicPermission,omitempty" tf:"public_permission,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type OBSParameters_2 struct {

	// Specifies the object account permissions.
	// The account_permission_struct structure is documented below.
	// Specifies the object account permissions.
	// +kubebuilder:validation:Optional
	AccountPermission []AccountPermissionParameters `json:"accountPermission,omitempty" tf:"account_permission,omitempty"`

	// Specifies the name of the bucket which the object belongs to.
	// Specifies the name of the bucket which the object belongs to.
	// +crossplane:generate:reference:type=OBS
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a OBS to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v1.Reference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a OBS to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v1.Selector `json:"bucketSelector,omitempty" tf:"-"`

	// Specifies the name of the object to which to set the acl.
	// Specifies the name of the object to which to set the acl.
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Specifies the object public permission.
	// The permission_struct structure is documented below.
	// Specifies the object public permission.
	// +kubebuilder:validation:Optional
	PublicPermission []PublicPermissionParameters `json:"publicPermission,omitempty" tf:"public_permission,omitempty"`

	// Specifies the region in which to create the resource.
	// If omitted, the provider-level region will be used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type OwnerPermissionInitParameters struct {
}

type OwnerPermissionObservation struct {

	// Specifies the access to acl. Valid values are READ_ACP and WRITE_ACP.
	AccessToACL []*string `json:"accessToAcl,omitempty" tf:"access_to_acl,omitempty"`

	// Specifies the access to object. Only READ supported.
	AccessToObject []*string `json:"accessToObject,omitempty" tf:"access_to_object,omitempty"`
}

type OwnerPermissionParameters struct {
}

type PublicPermissionInitParameters struct {

	// Specifies the access to acl. Valid values are READ_ACP and WRITE_ACP.
	// Specifies the access to acl. Valid values are **READ_ACP** and **WRITE_ACP**.
	AccessToACL []*string `json:"accessToAcl,omitempty" tf:"access_to_acl,omitempty"`

	// Specifies the access to object. Only READ supported.
	// Specifies the access to object. Only **READ** supported.
	AccessToObject []*string `json:"accessToObject,omitempty" tf:"access_to_object,omitempty"`
}

type PublicPermissionObservation struct {

	// Specifies the access to acl. Valid values are READ_ACP and WRITE_ACP.
	// Specifies the access to acl. Valid values are **READ_ACP** and **WRITE_ACP**.
	AccessToACL []*string `json:"accessToAcl,omitempty" tf:"access_to_acl,omitempty"`

	// Specifies the access to object. Only READ supported.
	// Specifies the access to object. Only **READ** supported.
	AccessToObject []*string `json:"accessToObject,omitempty" tf:"access_to_object,omitempty"`
}

type PublicPermissionParameters struct {

	// Specifies the access to acl. Valid values are READ_ACP and WRITE_ACP.
	// Specifies the access to acl. Valid values are **READ_ACP** and **WRITE_ACP**.
	// +kubebuilder:validation:Optional
	AccessToACL []*string `json:"accessToAcl,omitempty" tf:"access_to_acl,omitempty"`

	// Specifies the access to object. Only READ supported.
	// Specifies the access to object. Only **READ** supported.
	// +kubebuilder:validation:Optional
	AccessToObject []*string `json:"accessToObject,omitempty" tf:"access_to_object,omitempty"`
}

// OBSSpec defines the desired state of OBS
type OBSSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OBSParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OBSInitParameters_2 `json:"initProvider,omitempty"`
}

// OBSStatus defines the observed state of OBS.
type OBSStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OBSObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OBS is the Schema for the OBSs API. ""
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,huaweicloud}
type OBS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	Spec   OBSSpec   `json:"spec"`
	Status OBSStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OBSList contains a list of OBSs
type OBSList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OBS `json:"items"`
}

// Repository type metadata.
var (
	OBS_Kind             = "OBS"
	OBS_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OBS_Kind}.String()
	OBS_KindAPIVersion   = OBS_Kind + "." + CRDGroupVersion.String()
	OBS_GroupVersionKind = CRDGroupVersion.WithKind(OBS_Kind)
)

func init() {
	SchemeBuilder.Register(&OBS{}, &OBSList{})
}
