apiVersion: teo.tencentcloud.crossplane.io/v1alpha1
kind: OriginGroup
metadata:
  annotations:
    meta.upbound.io/example-id: teo/v1alpha1/origingroup
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    name: keep-group-1
    records:
    - private: true
      privateParameters:
      - name: SecretAccessKey
        value: test
      record: tf-teo.xyz
      type: IP_DOMAIN
      weight: 100
    type: GENERAL
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
